local status, outline = pcall(require, "symbols-outline")
if not status then
	return
end

outline.setup({
	highlight_hovered_item = true,
	show_guides = true,
	auto_preview = false,
	position = "right",
	relative_width = true,
	width = 25,
	auto_close = false,
	show_numbers = false,
	show_relative_numbers = false,
	show_symbol_details = true,
	preview_bg_highlight = "Pmenu",
	autofold_depth = nil,
	auto_unfold_hover = true,
	fold_markers = { "", "" },
	wrap = false,
	keymaps = { -- These keymaps can be a string or a table for multiple keys
		close = { "<Esc>", "q" },
		goto_location = "<Cr>",
		focus_location = "o",
		hover_symbol = "<C-space>",
		toggle_preview = "K",
		rename_symbol = "r",
		code_actions = "a",
		fold = "h",
		unfold = "l",
		fold_all = "W",
		unfold_all = "E",
		fold_reset = "R",
	},
	lsp_blacklist = {},
	symbol_blacklist = {},
	symbols = {
		File = { icon = "", hl = "CmpItemKindURI" },
		Module = { icon = "", hl = "CmpItemKindModule" },
		Namespace = { icon = "", hl = "CmpItemKindNamespace" },
		Package = { icon = "", hl = "CmpItemKindPackage" },
		Class = { icon = "𝓒", hl = "CmpItemKindType" },
		Method = { icon = "", hl = "CmpItemKindMethod" },
		Property = { icon = "", hl = "CmpItemKindProperty" },
		Field = { icon = "", hl = "CmpItemKindField" },
		Constructor = { icon = "", hl = "CmpItemKindConstructor" },
		Enum = { icon = "ℰ", hl = "CmpItemKindEnum" },
		Interface = { icon = "ﰮ", hl = "CmpItemKindType" },
		Function = { icon = "", hl = "CmpItemKindFunction" },
		Variable = { icon = "", hl = "CmpItemKindVariable" },
		Constant = { icon = "", hl = "CmpItemKindConstant" },
		String = { icon = "𝓐", hl = "CmpItemKindString" },
		Number = { icon = "#", hl = "CmpItemKindNumber" },
		Boolean = { icon = "⊨", hl = "CmpItemKindBoolean" },
		Array = { icon = "", hl = "CmpItemKindConstant" },
		Object = { icon = "⦿", hl = "CmpItemKindObject" },
		Key = { icon = "🔐", hl = "CmpItemKindType" },
		Null = { icon = "NULL", hl = "CmpItemKindType" },
		EnumMember = { icon = "", hl = "CmpItemKindField" },
		Struct = { icon = "𝓢", hl = "CmpItemKindStruct" },
		Event = { icon = "🗲", hl = "CmpItemKindEvent" },
		Operator = { icon = "+", hl = "CmpItemKindOperator" },
		TypeParameter = { icon = "𝙏", hl = "CmpItemKindParameter" },
	},
})
